const products = [
  {
    id: 1,
    imgURL: "/assets/coffee.jpg",
    name: "Coffee",
    price: "$3.99",
    category: "All",
  },
  {
    id: 2,
    imgURL: "/assets/image/earring.jpg",
    name: "Earring",
    price: "$19.99",
    category: "Accessories",
  },
  {
    id: 3,
    imgURL: "/assets/image/extension.jpg",
    name: "Extension",
    price: "$15.99",
    category: "Home",
  },
  {
    id: 4,
    imgURL: "/assets/image/football.jpg",
    name: "Football",
    price: "$25.99",
    category: "Sports",
  },
  {
    id: 5,
    imgURL: "/assets/image/whiteball.jpg",
    name: "White Ball",
    price: "$32.99",
    category: "Sports",
  },
  {
    id: 6,
    imgURL: "/assets/image/spec.jpg",
    name: "Specs",
    price: "$12.99",
    category: "Accessories",
  },
  {
    id: 7,
    imgURL: "/assets/image/headphone.jpg",
    name: "Headphones",
    price: "$21.99",
    category: "Electronics",
  },
  {
    id: 8,
    imgURL: "/assets/image/lamp.jpg",
    name: "Lamp",
    price: "$20.99",
    category: "Home",
  },
  {
    id: 9,
    imgURL: "/assets/image/plug.jpg",
    name: "Plug",
    price: "$19.99",
    category: "Home",
  },
  {
    id: 10,
    imgURL: "/assets/image/shoe.jpg",
    name: "Shoe",
    price: "$29.99",
    category: "Footwear",
  },
  {
    id: 11,
    imgURL: "/assets/image/shoe1.jpg",
    name: "Sneaker",
    price: "$39.99",
    category: "Footwear",
  },
  {
    id: 12,
    imgURL: "/assets/image/sneakers.jpg",
    name: "Sneaker",
    price: "$49.99",
    category: "Footwear",
  },
  {
    id: 13,
    imgURL: "/assets/image/speaker.jpg",
    name: "Speaker",
    price: "$59.99",
    category: "All",
  },
];
export default products;
