const products = [
  {
    id: 1,
    img: "/assets/coffee.jpg",
    name: "Coffee",
    price: "$3.99",
    category: "All",
  },
  {
    id: 2,
    img: "/assets/image/earring.jpg",
    name: "Earring",
    price: "$19.99",
    category: "Accessories",
  },
  {
    id: 3,
    img: "./assets/extension.jpg",
    name: "Extension ",
    price: "$15.99",
    category: "Home",
  },
  {
    id: 4,
    img: "src/assets/football.jpg",
    name: "Football",
    price: "$25.99",
    category: "Sports",
  },
  {
    id: 5,
    img: "src/assets/whiteball.jpg",
    name: "White Ball",
    price: "$32.99",
    category: "Sports",
  },
  {
    id: 6,
    img: "src/assets/spec.jpg",
    name: "Specs",
    price: "$12.99",
    category: "Accessories",
  },
  {
    id: 7,
    img: "src/assets/headphonejpg",
    name: "Headphones",
    price: "$21.99",
    category: "Electronics",
  },
  {
    id: 8,
    img: "src/assets/lamp.jpg",
    name: "Lamp",
    price: "$20.99",
    category: "Home",
  },
  {
    id: 9,
    img: "src/assets/plug.jpg",
    name: "Plug",
    price: "$19.99",
    category: "Home",
  },
  {
    id: 10,
    img: "src/assets/shoe.jpg",
    name: "Shoe",
    price: "$29.99",
    category: "Footwear",
  },
  {
    id: 11,
    img: "src/assets/shoe1.jpg",
    name: "Sneaker",
    price: "$39.99",
    category: "Footwear",
  },
  {
    id: 12,
    img: "src/assets/sneaker.jpg",
    name: "Sneaker",
    price: "$49.99",
    category: "Footwear",
  },
  {
    id: 13,
    img: "src/assets/speaker.jpg",
    name: "Speaker",
    price: "$59.99",
    category: "All",
  },
];
export default products;
